### ISSUE TITLE
<NoMethodError> undefined method `code' on execute 'SendDTMF'

### ISSUE THREAD

**Issue by jsgoecke** [adhearsion/adhearsion-asterisk#7]
line 12 of modem.rb:

``` ruby
      execute 'SendDTMF', '#12345', 125
```

Causes this error:

```
[2012-06-21 18:32:22] ERROR Adhearsion::Call: f947beee-d548-4b1b-b573-45e6a58c173c: <NoMethodError> undefined method `code' for #<Punchblock::Event::Complete::Hangup:0x007ff6eb52d020>
    /Users/doug/.rvm/gems/ruby-1.9.3-p194@adhearsion/gems/adhearsion-asterisk-1.2.0/lib/adhearsion/asterisk/call_controller_methods.rb:21:in `block in agi'
    /Users/doug/.rvm/gems/ruby-1.9.3-p194@adhearsion/gems/adhearsion-asterisk-1.2.0/lib/adhearsion/asterisk/call_controller_methods.rb:21:in `map'
    /Users/doug/.rvm/gems/ruby-1.9.3-p194@adhearsion/gems/adhearsion-asterisk-1.2.0/lib/adhearsion/asterisk/call_controller_methods.rb:21:in `agi'
    /Users/doug/.rvm/gems/ruby-1.9.3-p194@adhearsion/gems/adhearsion-asterisk-1.2.0/lib/adhearsion/asterisk/call_controller_methods.rb:37:in `execute'
    /Users/doug/Projects/adhearsion/test/lib/modem.rb:12:in `run'
    /Users/doug/.rvm/gems/ruby-1.9.3-p194@adhearsion/gems/adhearsion-2.0.1/lib/adhearsion/call_controller.rb:83:in `execute!'
    /Users/doug/.rvm/gems/ruby-1.9.3-p194@adhearsion/gems/adhearsion-2.0.1/lib/adhearsion/call_controller.rb:45:in `block in exec'
    /Users/doug/.rvm/gems/ruby-1.9.3-p194@adhearsion/gems/adhearsion-2.0.1/lib/adhearsion/call_controller.rb:44:in `catch'
    /Users/doug/.rvm/gems/ruby-1.9.3-p194@adhearsion/gems/adhearsion-2.0.1/lib/adhearsion/call_controller.rb:44:in `exec'
    /Users/doug/.rvm/gems/ruby-1.9.3-p194@adhearsion/gems/adhearsion-2.0.1/lib/adhearsion/call.rb:295:in `block (2 levels) in execute_controller'
    /Users/doug/.rvm/gems/ruby-1.9.3-p194@adhearsion/gems/adhearsion-2.0.1/lib/adhearsion/foundation/exception_handler.rb:6:in `catching_standard_errors'
    /Users/doug/.rvm/gems/ruby-1.9.3-p194@adhearsion/gems/adhearsion-2.0.1/lib/adhearsion/call.rb:293:in `block in execute_controller'
```

**Comment by benlangfeld** [comment]
Fixed in 4a54af0b95c829e50e29d6b95c63046f31287383. Release coming soon
